
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 19 19:46:10 EST 2017
//----------------------------------------------------

package compiler488.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WITHX = 24;
  public static final int DIVIDE = 42;
  public static final int WHEN = 22;
  public static final int FUNCTION = 9;
  public static final int L_PAREN = 26;
  public static final int INTEGER = 8;
  public static final int R_SQUARE = 29;
  public static final int GREATER = 33;
  public static final int REPEAT = 16;
  public static final int R_PAREN = 27;
  public static final int MINUS = 40;
  public static final int LESS = 34;
  public static final int WRITE = 25;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int INTCONST = 44;
  public static final int OR = 3;
  public static final int COMMA = 35;
  public static final int R_CURLEY = 31;
  public static final int UNTIL = 20;
  public static final int PLUS = 39;
  public static final int EXIT = 13;
  public static final int IF = 14;
  public static final int DOT = 36;
  public static final int EOF = 0;
  public static final int BOOLEAN = 7;
  public static final int RETURN = 17;
  public static final int EQUAL = 32;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int NEWLINE = 18;
  public static final int IDENT = 43;
  public static final int TIMES = 41;
  public static final int COLON = 38;
  public static final int ELSE = 12;
  public static final int L_SQUARE = 28;
  public static final int READ = 15;
  public static final int WHILE = 23;
  public static final int THEN = 19;
  public static final int TEXTCONST = 45;
  public static final int QUESTION = 37;
  public static final int L_CURLEY = 30;
  public static final int FALSE = 6;
  public static final int VAR = 21;
  public static final int PROCEDURE = 10;
  public static final int DO = 11;
}

