TEST_DIRS="declarations expressions-types expressoin-type-checking functions-procedures-and-arguments scopes-and-programs statement-checking"

COMPILER="../dist/compiler488.jar"
FLAGS=""

all: $(TEST_DIRS)
