package compiler488.codegen;

import compiler488.runtime.Machine;

import java.util.ArrayList;

/**
 * Created by isthisnagee on 4/3/17.
 */
public class MachineUtils {
    /**
     * Get the number of lines generated by this sequence of instructions
     * @param instruction
     */
    public static int numLines(ArrayList<Instruction> instruction) {
       return instruction.size();
    }

    /**
     * Return a check for `a > b`
     * @param a
     * @param b
     * @return
     */
    public ArrayList<Instruction> MachineGT(ArrayList<Instruction> a, ArrayList<Instruction> b) {
        ArrayList<Instruction> result = new ArrayList<>();
        result.addAll(b);
        result.addAll(a);
        result.add(new Instruction(Machine.LT));
        return result;
    }

    /**
     * Return instructinos for `a >= b`
     * @param a
     * @param b
     * @return
     */
    public static ArrayList<Instruction> MachineGTE(ArrayList<Instruction> a, ArrayList<Instruction> b) {
        return new ArrayList<>();
    }

    /**
     * Return instructinos for `a <= b`
     * @param a
     * @param b
     * @return
     */
    public static ArrayList<Instruction> MachineLTE(ArrayList<Instruction> a, ArrayList<Instruction> b) {
        return new ArrayList<>();
    }

    public static ArrayList<Instruction> ifThenElse(ArrayList<Instruction> conditionInstructions, ArrayList<Instruction> trueBlock, ArrayList<Instruction> falseBlock) {
        ArrayList<Instruction> output = new ArrayList<>();

        int lastConditionInst = conditionInstructions.size() - 1;
        int offset = conditionInstructions.get(lastConditionInst).getLineNumber();

        int breakLines = 2;
        int trueLines = MachineUtils.numLines(trueBlock);
        int falseLines = MachineUtils.numLines(falseBlock);

		/* TODO: might need a -1 */
        int trueLineStart = offset + breakLines;
        int falseLineStart = trueLineStart + trueLines + breakLines;
        int exitLine = falseLineStart + falseLines;

		/*
		 codegen(condition)
		 PUSH <else start>
		 BF
		 codegen(trueblock)
		 PUSH <exit line>
		 BR (exit)
		 codegen(falseblock)
		 // exit line num
		 */
        output.addAll(conditionInstructions);
        output.add(new Instruction(Machine.PUSH, falseLineStart));
        output.add(new Instruction(Machine.BF));

        output.addAll(trueBlock);
        output.add(new Instruction(Machine.PUSH, exitLine));
        output.add(new Instruction(Machine.BR));

        output.addAll(falseBlock);

		/* jump to true, and true */

        return output;
    }
}
